# Generated by Django 4.2.1 on 2024-03-19 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='available_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='contact',
            field=models.CharField(default=99787478454, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='gst_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
