# Generated by Django 4.2.1 on 2024-03-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_store_address_store_available_capacity_store_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='available_capacity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gst_num',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_capacity',
        ),
    ]
