# Generated by Django 4.2.1 on 2024-02-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('cm', 'Cm'), ('metre', 'Metre'), ('inches', 'Inches'), ('oz', 'Oz'), ('litre', 'Litre'), ('ml', 'ML'), ('mm', 'MM'), ('ton', 'Ton'), ('grams', 'Grams')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'variants',
                'db_table': 'variant',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fk_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.tag')),
            ],
            options={
                'verbose_name_plural': 'taxes',
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(verbose_name='product description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product base price')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product selling price')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product MRP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='product creation date')),
                ('discount', models.ManyToManyField(blank=True, null=True, to='store_app.discount', verbose_name='product Discount')),
                ('fk_category', models.ManyToManyField(to='store_app.category', verbose_name='product category')),
                ('fk_extra_detail', models.ManyToManyField(blank=True, null=True, to='store_app.extradetails', verbose_name='product detail')),
                ('fk_tag', models.ManyToManyField(to='store_app.tag', verbose_name='product tag')),
                ('fk_tax', models.ManyToManyField(blank=True, null=True, to='store_app.tax', verbose_name='product Tax')),
                ('fk_variant', models.ManyToManyField(to='store_app.variant', verbose_name='product variant')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='extradetails',
            name='fk_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='discount',
            name='fk_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.tax'),
        ),
        migrations.AddField(
            model_name='category',
            name='fk_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.tag', verbose_name='Tag'),
        ),
    ]
