# Generated by Django 4.2.1 on 2024-02-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0003_otherdetail_othertax_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'warehouses'},
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='conatact',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='fk_other_detail',
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='product_total_valuation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Updated by user'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fk_other_detail',
            field=models.ManyToManyField(to='store_app.otherdetail', verbose_name='Other Details'),
        ),
    ]
