# Generated by Django 4.2.1 on 2024-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_discount_fk_tax_discount_discount_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
