# Generated by Django 4.2.1 on 2024-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_inventory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='fk_other_detail',
            field=models.ManyToManyField(blank=True, null=True, to='store_app.otherdetail', verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='fk_tag',
            field=models.ManyToManyField(to='store_app.tag'),
        ),
    ]
