# Generated by Django 4.2.1 on 2024-03-27 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0008_alter_warehouseinventory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='adjusted_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='tag_name',
            field=models.CharField(default=datetime.datetime(2024, 3, 27, 7, 1, 14, 858268, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='damage_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.product', verbose_name='Log of inventory product'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='fk_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.warehouse', verbose_name='Log of warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='reason',
            field=models.CharField(choices=[('Coorelation', 'Coolreation'), ('Count', 'Count'), ('Recieved', 'Recieved'), ('Damaged', 'Damaged'), ('Return Restock', 'Return Restock'), ('Theft or loss', 'Theft or loss'), ('Promotion or donation', 'Promotion or donation')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Updated by User'),
        ),
    ]
